export const campoEmailLogin = (<HTMLInputElement>document.getElementById('username'))
export const campoSenhaLogin = (<HTMLInputElement>document.getElementById('password'))
export const campoTipoLogin = (<HTMLInputElement>document.getElementById('opcao-login'))

export const campoSenhaExclusaoCandidato = (<HTMLInputElement>document.getElementById('senha-excluir'))
export const campoIdExclusaoVaga = (<HTMLInputElement>document.getElementById('id-exclusao'))

export const campoNomeCandidato = (<HTMLInputElement>document.getElementById('nome-candidato'))
export const campoCpfCandidato = (<HTMLInputElement>document.getElementById('cpf-candidato'))
export const campoIdadeCandidato = (<HTMLInputElement>document.getElementById('idade-candidato'))
export const campoEmailCandidato = (<HTMLInputElement>document.getElementById('email-candidato'))
export const campoSenhaCandidato = (<HTMLInputElement>document.getElementById('password-candidato'))
export const campoEstadoCandidato = (<HTMLInputElement>document.getElementById('estado-candidato'))
export const campoCepCandidato = (<HTMLInputElement>document.getElementById('cep-candidato'))
export const campoDescricaoCandidato = (<HTMLInputElement>document.getElementById('descricao-candidato'))

export const campoCompetenciaCandidato0 = (<HTMLInputElement>document.getElementById('0c'))
export const campoCompetenciaCandidato1 = (<HTMLInputElement>document.getElementById('1c'))
export const campoCompetenciaCandidato2 = (<HTMLInputElement>document.getElementById('2c'))
export const campoCompetenciaCandidato3 = (<HTMLInputElement>document.getElementById('3c'))
export const campoCompetenciaCandidato4 = (<HTMLInputElement>document.getElementById('4c'))
export const campoCompetenciaCandidato5 = (<HTMLInputElement>document.getElementById('5c'))

export const campoNomeEmpresa = (<HTMLInputElement>document.getElementById('nome-empresa'))
export const campoCnpjEmpresa = (<HTMLInputElement>document.getElementById('cnpj-empresa'))
export const campoEmailEmpresa = (<HTMLInputElement>document.getElementById('email-empresa'))
export const campoSenhaEmpresa = (<HTMLInputElement>document.getElementById('password-empresa'))
export const campoPaisEmpresa = (<HTMLInputElement>document.getElementById('pais-empresa'))
export const campoEstadoEmpresa = (<HTMLInputElement>document.getElementById('estado-empresa'))
export const campoCepEmpresa = (<HTMLInputElement>document.getElementById('cep-empresa'))
export const campoDescricaoEmpresa = (<HTMLInputElement>document.getElementById('descricao-empresa'))

export const campoNomeVaga = (<HTMLInputElement>document.getElementById('nome-vaga'))
export const campoIdVaga = (<HTMLInputElement>document.getElementById('id-vaga'))
export const campoEstadoVaga = (<HTMLInputElement>document.getElementById('estado-vaga'))
export const campoCidadeVaga = (<HTMLInputElement>document.getElementById('cidade-vaga'))
export const campoDescricaoVaga = (<HTMLInputElement>document.getElementById('descricao-vaga'))

export const campoCompetenciaVaga0 = (<HTMLInputElement>document.getElementById('0e'))
export const campoCompetenciaVaga1 = (<HTMLInputElement>document.getElementById('1e'))
export const campoCompetenciaVaga2 = (<HTMLInputElement>document.getElementById('2e'))
export const campoCompetenciaVaga3 = (<HTMLInputElement>document.getElementById('3e'))
export const campoCompetenciaVaga4 = (<HTMLInputElement>document.getElementById('4e'))
export const campoCompetenciaVaga5 = (<HTMLInputElement>document.getElementById('5e'))

